---
- name: Create GCP webserver(s) resources
  hosts: all
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  #environment:
    #GCP_SERVICE_ACCOUNT_EMAIL: "{{ lookup('env','GCE_EMAIL') }}"
    #GCP_SCOPES: "https://www.googleapis.com/auth/compute"

  roles:
    - role: gcpweb
